language: minimal

git:
    depth: 1

sudo: false

dist: xenial

branches:
  except:
    - /^Last_.*/

os:
    - linux

services:
    - docker

addons:
  apt:
    update: true
    packages:
      - postgresql-client
      - mysql-client
      - pgloader


before_install:
  - docker pull mysql
  - docker pull postgres

script:
  - docker run -d -p 127.0.0.1:3306:33060 --name mysql -e MYSQL_DATABASE=tbcmangos -e MYSQL_USER=mangos -e MYSQL_PASSWORD=mangos -e MYSQL_ROOT_PASSWORD=mangos mysql
  - docker run -d -p 127.0.0.1:5432:5432 --name postgres -e POSTGRES_DB=tbcmangos -e POSTGRES_USER=mangos -e POSTGRES_PASSWORD=mangos postgres
  - echo "Sleeping for 60s waiting for containers to spin up"
  - sleep 60
  - docker ps -a
  - docker logs mysql --details
  - docker logs postgres --details
  - mysql -h 127.0.0.1 -u mangos -pmangos -e "SHOW DATABASES;"
  - echo "DB_HOST=\"127.0.0.1\"" >> InstallFullDB.config
  - echo "DATABASE=\"mangos\"" >> InstallFullDB.config
  - echo "USERNAME=\"mangos\"" >> InstallFullDB.config
  - echo "PASSWORD=\"\"" >> InstallFullDB.config
  - echo "MYSQL=\"mysql\"" >> InstallFullDB.config
  - cat InstallFullDB.config
  - ./InstallFullDB.sh
  - mysqldump -h 127.0.0.1 -u mangos -pmangos mangos >> FullDB.sql
  - pgloader mysql://mangos:mangos@127.0.0.1/tbcmangos pgsql://mangos:mangos@127.0.0.1/tbcmangos
  - pg_dump -h 127.0.0.1 -u mangos -pmangos mangos > FullDB.bak
  - zip License.mdown FullDB.sql FullDB.bak FullDB.zip
  
deploy:
  provider: releases
  name: master-latest
  overwrite: true
  tag_name: master-latest
  prerelease: true
  api_key: "GITHUB OAUTH TOKEN"
  file: FullDB.zip
  skip_cleanup: true
