language: minimal

git:
    depth: 1

sudo: false

dist: xenial

branches:
  except:
    - /^Last_.*/

os:
    - linux

services:
    - docker
#    - mysql
#    - postgres

addons:
  apt:
    update: true
    packages:
      - postgresql-client
      - mysql-client
      - pgloader


before_install:
#  - mysql -e 'CREATE DATABASE tbcmangos'
#  - psql -c 'CREATE DATABASE tbcmangos;' -U postgres
  - docker pull mysql
  - docker pull postgres
  - docker run -d -p 127.0.0.1:3306:3306 --name mysql mysql -e MYSQL_DATABASE=tbcmangos MYSQL_USER=mangos MYSQL_PASSWORD=mangos
  - docker run -d -p 127.0.0.1:5432:5432 --name postgres postgres -e POSTGRES_DB=tbcmangos POSTGRES_USER=mangos POSTGRES_PASSWORD=mangos

script: |-
  docker ps
  mysql -h 127.0.0.1 -u mangos -pmangos -e "SHOW DATABASES;"
#  git clone --depth 1 https://github.com/cmangos/mangos-tbc.git ../mangos-tbc
  echo "DB_HOST=\"127.0.0.1\"" >> InstallFullDB.config
  echo "DATABASE=\"mangos\"" >> InstallFullDB.config
  echo "USERNAME=\"mangos\"" >> InstallFullDB.config
  echo "PASSWORD=\"\"" >> InstallFullDB.config
  echo "MYSQL=\"mysql\"" >> InstallFullDB.config
  cat InstallFullDB.config
  ./InstallFullDB.sh
  mysqldump -h 127.0.0.1 -u mangos -pmangos mangos >> FullDB.sql
  pgloader mysql://mangos:mangos@127.0.0.1/tbcmangos pgsql://mangos:mangos@127.0.0.1/tbcmangos
  pg_dump -h 127.0.0.1 -u mangos -pmangos mangos > FullDB.bak
  zip License.mdown FullDB.sql FullDB.bak FullDB.zip
  
  deploy:
    provider: releases
    name: master-latest
    overwrite: true
    tag_name: master-latest
    prerelease: true
    api_key: "GITHUB OAUTH TOKEN"
    file: FullDB.zip
    skip_cleanup: true
