language: minimal

git:
    depth: 1

sudo: false

dist: xenial

branches:
  except:
    - /^Last_.*/

os:
    - linux

services:
    - docker

addons:
  apt:
    update: true
    packages:
      - postgresql-client
      - mysql-client
      - pgloader
      - docker-compose


before_install:
  - docker pull mysql
  - docker pull postgres

script:
  - git clone --depth 1 https://github.com/cmangos/mangos-tbc.git
  - cd docker;docker-compose up -d; cd ..
  - echo "Sleeping for 10s waiting for containers to spin up"
  - sleep 10
  - mysql -h 127.0.0.1 -u mangos -pmangos -e "SHOW DATABASES;"
  - echo "DB_HOST=\"127.0.0.1\"" >> InstallFullDB.config
  - echo "DATABASE=\"tbcmangos\"" >> InstallFullDB.config
  - echo "USERNAME=\"mangos\"" >> InstallFullDB.config
  - echo "PASSWORD=\"mangos\"" >> InstallFullDB.config
  - echo "MYSQL=\"mysql\"" >> InstallFullDB.config
  - echo "CORE_PATH=\"./mangos-tbc\"" >> InstallFullDB.config
  - cat InstallFullDB.config
  - ./InstallFullDB.sh
  - mysqldump -h 127.0.0.1 -u mangos -pmangos tbcmangos >> FullDB.sql
  - pgloader --with right-trim mysql://mangos:mangos@127.0.0.1/tbcmangos pgsql://mangos:mangos@127.0.0.1/tbcmangos
  - pg_dump -h 127.0.0.1 -u mangos -pmangos tbcmangos > FullDB.bak
  - zip License.mdown FullDB.sql FullDB.bak FullDB.zip
  
deploy:
  provider: releases
  name: master-latest
  overwrite: true
  tag_name: master-latest
  prerelease: true
  api_key: "GITHUB OAUTH TOKEN"
  file: FullDB.zip
  skip_cleanup: true
