language: minimal

git:
    depth: 10

sudo: false

dist: trusty

branches:
  except:
    - /^Last_.*/

os:
    - linux

services:
    - postgresql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client


before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('mangos') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pmangos
  - sudo service mysql restart

script: |-
  export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
  git clone https://github.com/Lillecarl/mangos-tbc.git
  echo "DATABASE=\"mangos\"" >> InstallFullDB.config
  echo "USERNAME=\"root\"" >> InstallFullDB.config
  echo "PASSWORD=\"mangos\"" >> InstallFullDB.config
  echo "MYSQL=\"mysql\"" >> InstallFullDB.config
  cat InstallFullDB.config
  mysql -e "CREATE DATABASE mangos" -u root -pmangos
  ./InstallFullDB.sh
  mysqldump -u root -pmangos mangos >> FullDB.sql
  zip License.mdown FullDB.sql FullDB.zip
