language: minimal
git:
  depth: 1
sudo: false
dist: xenial
branches:
  except:
  - "/^Last_.*/"
os:
- linux
services:
- docker
addons:
  apt:
    update: true
    packages:
    - postgresql-client
    - mysql-client
    - pgloader
    - docker-compose
before_install:
- docker pull mysql
- docker pull postgres
- cd docker;docker-compose up -d; cd ..
- git clone --depth 1 https://github.com/cmangos/mangos-tbc.git
- echo "Sleeping for 15s waiting for containers to spin up"
- sleep 15
- echo "DB_HOST=\"127.0.0.1\"" >> InstallFullDB.config
- echo "DATABASE=\"tbcmangos\"" >> InstallFullDB.config
- echo "USERNAME=\"mangos\"" >> InstallFullDB.config
- echo "PASSWORD=\"mangos\"" >> InstallFullDB.config
- echo "MYSQL=\"mysql\"" >> InstallFullDB.config
- echo "CORE_PATH=\"./mangos-tbc\"" >> InstallFullDB.config
script:
- "./InstallFullDB.sh"
- docker exec pgloader pgloader -v mysql://mangos:mangos@172.28.1.3/tbcmangos pgsql://mangos:mangos@172.28.1.4/tbcmangos
- mysqldump -h 127.0.0.1 -u mangos -pmangos tbcmangos >> FullDB.sql
- PGPASSWORD=mangos pg_dump -Fc -h 127.0.0.1 -U mangos -d tbcmangos > FullDB.bak
- zip ~/FullDB.zip FullDB.bak FullDB.sql LICENSE.md 

deploy:
  provider: releases
  overwrite: true
  draft: true
  prerelease: true
  api_key:
    secure: TJmfPi18EsQKYs1iAtQ+av3bO8hMdhshefjPNEgjvLgluCxkJCBqadOMHkNfF1gxqEfPJ1IJQ6rFVo3Hr8VOkScQafsUtG3z6Nc/cvW+Ai5BWkOZYxS8kfKtA6/w6ZHK1mJjcgiHwWxrgE7Fe58YGN4xLLqfl1O3xkcSMW+gzL3X508AreG41A0S/T/8ZiMLTe13gWkGgKyNHoXpuu3fo2Ow+9ch3eAGTOanaGDARRXOj2g7ze9/Yeq8+JKS9nFxUb52t36KCtdw7E9zkVpnsWQ7fu/hi9/EGmPLO81qB8QPw5/pcUS8yaP/Q5ABL8AoC0Ei0KqVAWRhL6oUbpnmGnb43R46nBBriF9/nPwEqc6V7qCsPGMVfcQweuhsebt3mgKef4ar/opEZWhbSk6RA/bxHNPPY1FJ+xRVPi/UW5XA0W1JtuzUFQUH1mFPcdzNrYmcnDuzq8mx30bpp4y0LYDU6UgWwE4FaNK3+qkAYgGXJQr6EVQkO79SeSyFZvtlw6FeFhqjb1jjcIU76tStVNQl8W52urDgPqoYSYbYlLgBwiuH2tP38YthI0dYmspmWNIdpc8dwuANmUUQWRhF5kD6fD3d7RyMXO8nwCdwgYgyeKkPBqrIw5xDVkCjowJhwRxZ0M+4VoCewUy/pOc3IZwE/yg1JhtqoJB/RC0NKYc=
  file: ~/FullDB.zip
  on:
    repo: Lillecarl/tbc-db
