version: '3'
services:
    dbimporter:
        build: .
        depends_on:
         - mysql
         - postgres
    mysql:
        image: "mysql"
        ports:
         - "3306:3306"
        env_file:
         - mysql.env
    postgres:
        image: "postgres"
        ports:
         - "5432:5432"
        env_file:
         - postgres.env
 
