version: '3'
services:
    pgloader:
        container_name: pgloader
        build: .
        networks:
            testing_net:
                ipv4_address: 172.28.1.2
    mysql:
        image: "mysql:5"
        ports:
         - "3306:3306"
        env_file:
         - mysql.env
        networks:
            testing_net:
                ipv4_address: 172.28.1.3
    postgres:
        image: "postgres"
        ports:
         - "5432:5432"
        env_file:
         - postgres.env
        networks:
            testing_net:
                ipv4_address: 172.28.1.4
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
 
